# Generated by Django 5.2.16 on 2026-08-03 16:12

import apps.core.fields
import apps.core.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0003_initial'),
        ('guests', '0001_initial'),
        ('tenants', '0004_hotel_kiosk_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestFace',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('sequence', models.PositiveSmallIntegerField(default=1, help_text='1..n within one capture session.')),
                ('pose_hint', models.CharField(blank=True, help_text="What the guest was asked to do, e.g. 'look straight', 'turn left'.", max_length=32)),
                ('image', apps.core.fields.EncryptedTextField(blank=True, help_text='Base64 JPEG. Empty when raw storage is switched off.')),
                ('content_type', models.CharField(default='image/jpeg', max_length=40)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=0)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(choices=[('kiosk', 'Reception kiosk'), ('desk', 'Front desk'), ('pwa', 'Guest app')], default='kiosk', max_length=12)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Hard-deleted after this instant. Never null.')),
                ('consent', models.ForeignKey(blank=True, help_text='The recorded permission this capture relies on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_captures', to='guests.guestconsent')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='guests.guest')),
                ('reservation', models.ForeignKey(blank=True, help_text='The stay this capture was taken for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_captures', to='booking.reservation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'guest face capture',
                'verbose_name_plural': 'guest face captures',
                'ordering': ('guest', 'sequence'),
                'indexes': [models.Index(fields=['tenant', 'guest', 'sequence'], name='vision_gues_tenant__22bbb8_idx'), models.Index(fields=['expires_at'], name='vision_gues_expires_180c8f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('reservation__isnull', False)), fields=('reservation', 'sequence'), name='uniq_face_frame_per_reservation')],
            },
        ),
    ]
