# Generated by Django 5.2.16 on 2026-08-02 17:00

import apps.core.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_hotel_check_in_time_alter_hotel_check_out_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('number', models.CharField(db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('settled', 'Settled'), ('void', 'Void')], db_index=True, default='open', max_length=12)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('charges_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payments_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'folio',
                'verbose_name_plural': 'folios',
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='FolioLine',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('charge_type', models.CharField(choices=[('room', 'Room charge'), ('tax', 'Tax / VAT'), ('service', 'Service charge'), ('restaurant', 'Restaurant'), ('minibar', 'Minibar'), ('laundry', 'Laundry'), ('spa', 'Spa'), ('transport', 'Transport'), ('late_checkout', 'Late checkout'), ('damage', 'Damage / loss'), ('discount', 'Discount'), ('adjustment', 'Adjustment'), ('other', 'Other')], db_index=True, max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('business_date', models.DateField(db_index=True, help_text='Hotel business date, not the wall clock. Set by night audit.')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Negative for discounts and reversals.', max_digits=14)),
                ('source_module', models.CharField(blank=True, max_length=30)),
                ('source_ref', models.CharField(blank=True, max_length=64)),
                ('is_voided', models.BooleanField(db_index=True, default=False)),
                ('ai_suggested', models.BooleanField(default=False, help_text='The AI proposed this line; a human posted it (goal.txt D11).')),
            ],
            options={
                'verbose_name': 'folio line',
                'verbose_name_plural': 'folio lines',
                'ordering': ('business_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('number', models.CharField(db_index=True, max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('service_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('bill_to_name', models.CharField(blank=True, max_length=150)),
                ('bill_to_address', models.CharField(blank=True, max_length=255)),
                ('tax_registration_no', models.CharField(blank=True, max_length=50)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card (taken at desk)'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank_transfer', 'Bank transfer'), ('corporate', 'Corporate account'), ('online', 'Online gateway')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('void', 'Void')], db_index=True, default='captured', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, help_text='Card last 4, wallet trx id, or slip number.', max_length=100)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('provider_ref', models.CharField(blank=True, db_index=True, max_length=120)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='BusinessDate',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('current_date', models.DateField()),
                ('last_audit_at', models.DateTimeField(blank=True, null=True)),
                ('rooms_charged', models.PositiveIntegerField(default=0)),
                ('revenue_posted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_audit_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'business date',
                'verbose_name_plural': 'business dates',
                'ordering': ('-current_date',),
            },
        ),
    ]
