# Generated by Django 5.2.16 on 2026-08-02 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('booking', '0001_initial'),
        ('guests', '0001_initial'),
        ('tenants', '0002_alter_hotel_check_in_time_alter_hotel_check_out_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folios', to='guests.guest'),
        ),
        migrations.AddField(
            model_name='folio',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='folio', to='booking.reservation'),
        ),
        migrations.AddField(
            model_name='folio',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel'),
        ),
        migrations.AddField(
            model_name='folioline',
            name='folio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.folio'),
        ),
        migrations.AddField(
            model_name='folioline',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folioline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel'),
        ),
        migrations.AddField(
            model_name='folioline',
            name='voided_by_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voids', to='billing.folioline'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='folio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.folio'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='guests.guest'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel'),
        ),
        migrations.AddField(
            model_name='payment',
            name='folio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.folio'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel'),
        ),
        migrations.AddConstraint(
            model_name='businessdate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant',), name='uniq_business_date_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['tenant', 'status'], name='billing_fol_tenant__6557fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'number'), name='uniq_folio_number_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='folioline',
            index=models.Index(fields=['folio', 'business_date'], name='billing_fol_folio_i_392df0_idx'),
        ),
        migrations.AddIndex(
            model_name='folioline',
            index=models.Index(fields=['charge_type'], name='billing_fol_charge__8acb25_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'number'), name='uniq_invoice_number_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['folio', 'status'], name='billing_pay_folio_i_9da1dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('tenant', 'idempotency_key'), name='uniq_payment_idempotency_key'),
        ),
    ]
