# Generated by Django 5.2.16 on 2026-08-02 13:51

import apps.core.utils
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('channel', models.CharField(choices=[('kiosk', 'Reception kiosk'), ('web', 'Staff web'), ('pwa', 'Guest app'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone')], default='kiosk', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved by AI'), ('handoff', 'Handed to staff'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=20)),
                ('guest_name', models.CharField(blank=True, max_length=150, verbose_name='guest name')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('language', models.CharField(default='en', max_length=8)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('turn_count', models.PositiveSmallIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('handoff_reason', models.CharField(blank=True, choices=[('low_confidence', 'AI confidence below threshold'), ('repeated', 'Guest repeated the same question'), ('blocked_topic', 'Blocked topic'), ('turn_limit', 'Conversation turn limit reached'), ('guest_request', 'Guest asked for a human'), ('ai_unavailable', 'AI unavailable — manual mode'), ('error', 'AI error')], db_index=True, max_length=30)),
                ('satisfaction', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Handoff',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('reason', models.CharField(choices=[('low_confidence', 'AI confidence below threshold'), ('repeated', 'Guest repeated the same question'), ('blocked_topic', 'Blocked topic'), ('turn_limit', 'Conversation turn limit reached'), ('guest_request', 'Guest asked for a human'), ('ai_unavailable', 'AI unavailable — manual mode'), ('error', 'AI error')], max_length=30)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='reception.conversation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'handoff request',
                'verbose_name_plural': 'handoff queue',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'Guest'), ('assistant', 'AI'), ('staff', 'Staff')], max_length=12)),
                ('content', models.TextField()),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('citations', models.JSONField(blank=True, default=list, help_text='Sources the answer was drawn from. Empty means unsourced.')),
                ('was_spoken', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='reception.conversation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant', 'status', '-started_at'], name='reception_c_tenant__5c972e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['channel', '-started_at'], name='reception_c_channel_107d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='handoff',
            index=models.Index(fields=['tenant', 'resolved_at', 'created_at'], name='reception_h_tenant__10def4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='reception_m_convers_bd47f5_idx'),
        ),
    ]
