# Generated by Django 5.2.16 on 2026-08-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='booking_draft',
            field=models.JSONField(blank=True, default=dict, help_text='Work-in-progress booking. Cleared once the reservation is created.'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='mode',
            field=models.CharField(choices=[('chat', 'Answering questions'), ('booking', 'Taking a booking')], default='chat', max_length=12),
        ),
    ]
