# Generated by Django 5.2.16 on 2026-08-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_conversation_booking_draft_conversation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='language_confirmed',
            field=models.BooleanField(default=False, help_text='The guest has settled the language, either by naming one or simply by asking a question. Until then the kiosk offers the choice.'),
        ),
    ]
