# Generated by Django 5.2.16 on 2026-08-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_conversation_language_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='channel',
            field=models.CharField(choices=[('kiosk', 'Reception kiosk'), ('web', 'Staff web'), ('website', 'Website'), ('pwa', 'Guest app'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone')], default='kiosk', max_length=20),
        ),
    ]
