"""Write user.txt: every account, its hotel, its role and what it can open.

    python manage.py dump_users            # writes ./user.txt
    python manage.py dump_users --stdout   # print instead

The account list comes from the database, so the file cannot drift out of date
the way a hand-maintained credentials note always does.

Passwords are NOT in the database in plaintext — they are PBKDF2 hashes. The
values written here are the known seed passwords for accounts this project
created (``bootstrap_hotel`` and ``seed_demo``); anything else is reported as
"unknown", which is the honest answer.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand, CommandError

from apps.accounts.models import Role, RoleCode
from apps.core.demo_data import DEMO_EMPLOYEE_PREFIX, DEMO_PASSWORD
from apps.core.navigation import NAVIGATION
from apps.tenants.models import HotelMembership

User = get_user_model()

ROLE_ORDER = [
    RoleCode.SUPERADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.AI_RECEPTION,
]


class Command(BaseCommand):
    help = "Write user.txt with every account, role and module access."

    def add_arguments(self, parser: Any) -> None:
        parser.add_argument("--output", default="user.txt")
        parser.add_argument("--stdout", action="store_true", help="Print instead of writing.")
        parser.add_argument(
            "--admin-password",
            default="",
            help="Plaintext for the superuser account, if you know it.",
        )
        parser.add_argument(
            "--set-password",
            default="",
            help=(
                "Set the superuser's password to this and record it. Use when nobody "
                "knows it any more — a hash cannot be read back."
            ),
        )

    def handle(self, *args: Any, **options: Any) -> None:
        admin_password = options["admin_password"]

        # --admin-password only WRITES a password down, which is worth nothing if
        # nobody knows it: Django stores a PBKDF2 hash and there is nothing to read
        # back. --set-password sets it first, so the file is true by construction
        # rather than by somebody remembering correctly.
        if options["set_password"]:
            if admin_password and admin_password != options["set_password"]:
                raise CommandError("--admin-password and --set-password disagree.")
            admin_password = options["set_password"]
            changed = []
            for user in User.objects.filter(is_superuser=True):
                user.set_password(admin_password)
                user.save(update_fields=["password"])
                changed.append(user.email)
            if not changed:
                raise CommandError("No superuser to set a password on.")
            self.stdout.write(self.style.WARNING("  password set for " + ", ".join(changed)))

        lines = self._build(admin_password)
        text = "\n".join(lines) + "\n"

        if options["stdout"]:
            self.stdout.write(text)
            return

        path = Path(settings.BASE_DIR) / options["output"]
        path.write_text(text, encoding="utf-8")
        self.stdout.write(
            self.style.SUCCESS(f"{path.name} written — {User.objects.count()} accounts")
        )
        self.stdout.write(
            self.style.WARNING("  Contains plaintext passwords. It is git-ignored. Keep it local.")
        )

    # ------------------------------------------------------------------ build

    def _build(self, admin_password: str) -> list[str]:
        out: list[str] = []
        add = out.append

        module_map = self._module_map()

        add("=" * 80)
        add("ASHOS — USER ACCOUNTS AND PASSWORDS")
        add("=" * 80)
        add("Generated by: python manage.py dump_users   (reads the live database)")
        add("")

        # --- superuser, front and centre -------------------------------------
        superusers = User.objects.filter(is_superuser=True).order_by("email")
        add("-" * 80)
        add("SUPER ADMIN  —  Django admin and staff app")
        add("-" * 80)
        for user in superusers:
            add(f"  username   {user.email}")
            add(f"  password   {admin_password or 'unknown — run manage.py changepassword'}")
            add(f"  name       {user.full_name}")
            add("")
        # runserver's default. The file used to say :320, which is not a port this
        # project has ever listened on, and it is the first thing somebody copies.
        add("  Django admin   http://127.0.0.1:8000/admin/")
        add("  Staff app      http://127.0.0.1:8000/accounts/login/")
        add("  Online booking http://127.0.0.1:8000/book/?hotel=GLH-001")
        add("  Lobby kiosk    http://127.0.0.1:8000/reception/kiosk/?hotel=GLH-001")
        add("")
        add("  NOTE: the login field is labelled 'Username' on /admin/ but it takes the")
        add("  EMAIL. ASHOS uses email as the username field — there is no separate")
        add("  handle to remember.")
        add("")

        # --- which door each account uses -------------------------------------
        #
        # Worth its own section because getting it wrong produces an error message
        # that reads like a wrong password and is not one: /admin/ answers "Please
        # enter the correct email and password for a staff account" when the
        # credentials are right and `is_staff` is False. Every operational account is
        # in exactly that position, on purpose.
        admin_capable = User.objects.filter(is_staff=True).count()
        add("-" * 80)
        add("WHICH LOGIN PAGE")
        add("-" * 80)
        add("  Staff app  /accounts/login/   EVERY account below. This is the product:")
        add("                                roles, permissions, the modules a role can")
        add("                                open. Operational work happens here.")
        add("")
        add("  Django     /admin/            The platform superuser only — currently")
        add(f"  admin                         {admin_capable} account. It is Django's own")
        add("                                admin, and it does NOT check the role")
        add("                                permissions the app is built on: a session")
        add("                                there can edit any table in any hotel.")
        add("")
        add("  A staff account typing its password into /admin/ is told the email and")
        add("  password are for a non-staff account. That is `is_staff=False` talking,")
        add("  not a bad password — the same credentials work at /accounts/login/.")
        add("")
        add("  The User model states the rule: is_staff is \"Access to /admin/.")
        add("  Operational roles do not need this.\"")
        add("")
        add("SECURITY")
        add("  Plaintext credentials. Git-ignored, and must stay that way.")
        add("  Development accounts only. Before anyone else can reach this database,")
        add("  change every password or run `seed_demo --flush` and create real ones.")
        add("=" * 80)
        add("")

        # --- roles ------------------------------------------------------------
        add("-" * 80)
        add("ROLES")
        add("-" * 80)
        add(f"  {'ROLE':<15}{'PERMS':>6}   MODULES")
        for code in ROLE_ORDER:
            role = Role.objects.filter(code=code).first()
            if role is None:
                continue
            add(f"  {code:<15}{role.permissions.count():>6}   {module_map.get(code, '—')}")
        add("")
        add("  Sidebar visibility and URL access use the same core.access_* permission,")
        add("  so opening a module the role lacks returns 403, not a blank page.")
        add("")

        # --- accounts ---------------------------------------------------------
        memberships = HotelMembership.all_objects.select_related("user", "hotel", "role").order_by(
            "hotel__code", "role__code", "user__email"
        )
        grouped: dict[tuple[str, str], list[HotelMembership]] = {}
        for membership in memberships:
            grouped.setdefault((membership.hotel.code, membership.hotel.name), []).append(
                membership
            )

        add("-" * 80)
        add("ACCOUNTS")
        add("-" * 80)
        add(f"  Demo staff password: {DEMO_PASSWORD}")
        if admin_password:
            add(f"  Superuser password : {admin_password}")
        add("")

        for (code, name), rows in sorted(grouped.items()):
            add(f"  {code} — {name}")
            add(f"    {'EMAIL':<38}{'ROLE':<15}{'NAME':<22}PASSWORD")
            add("    " + "-" * 92)
            rows.sort(key=lambda m: (self._role_rank(m.role.code), m.user.email))
            for membership in rows:
                user = membership.user
                password = self._password_for(user, admin_password)
                add(f"    {user.email:<38}{membership.role.name:<15}{user.full_name:<22}{password}")
            add("")

        orphans = User.objects.exclude(
            pk__in=HotelMembership.all_objects.values("user_id")
        ).order_by("email")
        if orphans:
            add("  NO HOTEL ASSIGNED (cannot see any tenant data until given a membership)")
            for user in orphans:
                add(f"    {user.email:<38}{'—':<15}{user.full_name}")
            add("")

        # --- management -------------------------------------------------------
        add("-" * 80)
        add("MANAGING ACCOUNTS")
        add("-" * 80)
        add("  change password    manage.py changepassword <email>")
        add("  new platform admin manage.py createsuperuser")
        add("  new staff          /admin/accounts/user/add/ then add a membership at")
        add("                     /admin/tenants/hotelmembership/add/")
        add("  unlock (5 fails = 15 min lockout)")
        add(
            '                     manage.py shell -c "from django.contrib.auth import '
            "get_user_model as g; g().objects.filter(email='<email>')"
            '.update(locked_until=None, failed_login_count=0)"'
        )
        add("  drop demo users    manage.py seed_demo --flush")
        add("  refresh this file  manage.py dump_users --admin-password <pw>")
        add("")
        add("  Database credentials, ports and start/stop commands: runcommand.txt")
        add("=" * 80)
        return out

    # ---------------------------------------------------------------- helpers

    @staticmethod
    def _module_map() -> dict[str, str]:
        """Which nav items each role may open, derived from the seeded grants."""
        from apps.accounts.management.commands.seed_roles import MODULE_ACCESS

        labels = {item.key: item.label for item in NAVIGATION}
        result: dict[str, str] = {}
        for role_code, modules in MODULE_ACCESS.items():
            keys = (
                [item.key for item in NAVIGATION if item.key != "dashboard"]
                if "*" in modules
                else list(modules)
            )
            result[role_code] = "Dashboard · " + " · ".join(labels.get(k, k) for k in keys)
        return result

    @staticmethod
    def _role_rank(code: str) -> int:
        return ROLE_ORDER.index(code) if code in ROLE_ORDER else len(ROLE_ORDER)

    @staticmethod
    def _password_for(user, admin_password: str) -> str:
        if user.employee_code.startswith(DEMO_EMPLOYEE_PREFIX):
            return DEMO_PASSWORD
        if user.is_superuser and admin_password:
            return admin_password
        # Hashes are one-way. Saying "unknown" beats printing a stale guess.
        return "unknown — set with `manage.py changepassword`"
