# Generated by Django 5.2.16 on 2026-08-02 12:04

import apps.core.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('code', models.CharField(help_text='Short stable identifier, e.g. GLH-001. Appears on invoices.', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]{3,12}$', 'Uppercase letters, digits, dash.')], verbose_name='code')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='legal name')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='slug')),
                ('address_line1', models.CharField(blank=True, max_length=200, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='address line 2')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=80, verbose_name='state/division')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('country', models.CharField(default='BD', max_length=2, verbose_name='country')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=64, verbose_name='timezone')),
                ('currency', models.CharField(default='BDT', max_length=3, verbose_name='currency')),
                ('star_rating', models.PositiveSmallIntegerField(default=3, verbose_name='star rating')),
                ('total_rooms', models.PositiveIntegerField(default=0, verbose_name='total rooms')),
                ('check_in_time', models.TimeField(default='14:00', verbose_name='standard check-in')),
                ('check_out_time', models.TimeField(default='12:00', verbose_name='standard check-out')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='VAT %')),
                ('service_charge_rate', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='service charge %')),
                ('tax_registration_no', models.CharField(blank=True, max_length=50, verbose_name='BIN/VAT no')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hotels/logo/', verbose_name='logo')),
                ('accent_color', models.CharField(default='#6366F1', max_length=7, verbose_name='accent colour')),
                ('plan', models.CharField(choices=[('pilot', 'Pilot'), ('standard', 'Standard'), ('enterprise', 'Enterprise')], default='pilot', max_length=20)),
                ('ai_enabled', models.BooleanField(default=True, verbose_name='AI enabled')),
                ('ai_kill_switch', models.BooleanField(default=False, help_text='Immediately routes every AI surface to manual staff mode.', verbose_name='AI kill switch')),
                ('biometric_enabled', models.BooleanField(default=False, help_text='Requires documented legal sign-off before enabling (goal.txt R1).', verbose_name='face recognition enabled')),
                ('ai_daily_cost_cap_usd', models.DecimalField(decimal_places=2, default=25, max_digits=8)),
            ],
            options={
                'verbose_name': 'hotel',
                'verbose_name_plural': 'hotels',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active', 'plan'], name='tenants_hot_is_acti_0d7efe_idx')],
            },
        ),
        migrations.CreateModel(
            name='HotelMembership',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('is_default', models.BooleanField(default=False, help_text='Hotel selected automatically when this user signs in.', verbose_name='default hotel')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.hotel')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hotel membership',
                'verbose_name_plural': 'hotel memberships',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('hotel', 'user'), name='uniq_active_membership_per_hotel_user')],
            },
        ),
    ]
