# Generated by Django 5.2.16 on 2026-08-02 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(default=datetime.time(14, 0), verbose_name='standard check-in'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='standard check-out'),
        ),
    ]
