# Generated by Django 5.2.16 on 2026-08-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_hotel_check_in_time_alter_hotel_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='kiosk_capture_photo',
            field=models.BooleanField(default=False, help_text='Freezes a still for staff to see who is at the desk. Kept in the browser for the session and never uploaded unless face recognition is enabled with consent.', verbose_name='hold a photo during the session'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='kiosk_greeting_style',
            field=models.CharField(default='neutral', help_text='How the kiosk opens when a guest steps up. neutral · formal · islamic', max_length=16, verbose_name='kiosk greeting'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='kiosk_presence_detection',
            field=models.BooleanField(default=True, help_text='Camera watches for someone at the kiosk and greets automatically. Presence only — no identification, and nothing leaves the browser.', verbose_name='greet on approach'),
        ),
    ]
