# Generated by Django 5.2.16 on 2026-08-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_hotel_kiosk_capture_photo_hotel_kiosk_greeting_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='kiosk_language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', help_text='The language the kiosk opens in. Guests can still ask in either.', max_length=8, verbose_name='kiosk language'),
        ),
    ]
