# Generated by Django 5.2.16 on 2026-08-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_hotel_kiosk_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='kiosk_voice_gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('any', 'Whatever the device offers')], default='female', help_text='Preferred voice for spoken answers.', max_length=12, verbose_name='kiosk voice'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='kiosk_voice_name',
            field=models.CharField(blank=True, help_text="Exact provider voice id, e.g. 'nova' or 'shimmer' for OpenAI. Leave blank to let the provider choose one matching the preference above.", max_length=40, verbose_name='voice name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='kiosk_language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', help_text='The language the kiosk OPENS in. Each answer is then given in whatever language the guest actually used, so this is the greeting, not a limit.', max_length=8, verbose_name='kiosk language'),
        ),
    ]
