# Generated by Django 5.2.16 on 2026-08-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_hotel_kiosk_voice_gender_hotel_kiosk_voice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='kiosk_hands_free',
            field=models.BooleanField(default=True, help_text='Listen automatically instead of making the guest press a button. Only within an active conversation, and it stands down after a period of silence — a lobby microphone that is open all day also hears everyone walking past.', verbose_name='hands-free microphone'),
        ),
    ]
