# Generated by Django 5.2.16 on 2026-08-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_hotel_kiosk_hands_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='kiosk_avatar',
            field=models.ImageField(blank=True, help_text='Portrait shown beside the conversation. Transparent PNG, roughly 900x1200. Leave empty for the stylised orb.', null=True, upload_to='hotels/kiosk/', verbose_name='kiosk avatar'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='kiosk_backdrop',
            field=models.ImageField(blank=True, help_text='Lobby photograph behind the scene. Wide, e.g. 1920x1080.', null=True, upload_to='hotels/kiosk/', verbose_name='kiosk backdrop'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='kiosk_hint',
            field=models.CharField(blank=True, help_text='One short line under the scene, e.g. "You can ask me anything about our hotel services." Blank uses a sensible default.', max_length=120, verbose_name='kiosk hint'),
        ),
    ]
