# Generated by Django 5.2.16 on 2026-08-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_hotel_kiosk_avatar_hotel_kiosk_backdrop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="accepts_bkash",
            field=models.BooleanField(default=False, verbose_name="accepts bKash"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="accepts_card",
            field=models.BooleanField(default=True, verbose_name="accepts cards at the desk"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="accepts_cash",
            field=models.BooleanField(default=True, verbose_name="accepts cash"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="accepts_nagad",
            field=models.BooleanField(default=False, verbose_name="accepts Nagad"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="advance_wallet",
            field=models.CharField(
                blank=True,
                choices=[("", "No advance accepted"), ("bkash", "bKash"), ("nagad", "Nagad")],
                default="",
                max_length=16,
                verbose_name="advance wallet",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="advance_wallet_number",
            field=models.CharField(
                blank=True,
                help_text="Shown to guests only when an advance is required. Personal/merchant number.",
                max_length=32,
                verbose_name="advance wallet number",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="payment_note",
            field=models.CharField(
                blank=True,
                help_text="The property's own sentence about payment, shown to guests as written and quoted by the assistant. Overrides nothing — it is added to the terms above.",
                max_length=255,
                verbose_name="payment note",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="payment_timing",
            field=models.CharField(
                choices=[
                    ("on_arrival", "Nothing online — settled at the desk"),
                    ("advance", "Advance to the hotel's wallet before the room is held"),
                ],
                default="on_arrival",
                help_text="On arrival: nothing is taken online, the room is held and settled at the desk. Advance: the guest sends a deposit to the wallet below before the room is held.",
                max_length=16,
                verbose_name="when payment is due",
            ),
        ),
    ]
