# Generated by Django 5.2.16 on 2026-08-02 17:00

import apps.core.fields
import apps.core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_hotel_check_in_time_alter_hotel_check_out_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('dr', 'Dr'), ('prof', 'Prof')], max_length=8)),
                ('first_name', models.CharField(max_length=80, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='last name')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('nationality', models.CharField(blank=True, help_text='ISO country code.', max_length=2)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=16)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('language', models.CharField(default='en', help_text='Drives the language the AI replies in.', max_length=8)),
                ('tier', models.CharField(choices=[('standard', 'Standard'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('vip', 'VIP')], default='standard', max_length=16)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='e.g. {"floor": "high", "bed": "king", "view": "sea"} — feeds AI room recommendation.')),
                ('notes', models.TextField(blank=True, help_text='Internal. The guest never sees this.')),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('total_stays', models.PositiveIntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_stay_at', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'guest',
                'verbose_name_plural': 'guests',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='GuestConsent',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('purpose', models.CharField(choices=[('face', 'Face recognition'), ('marketing', 'Marketing messages'), ('processing', 'Data processing'), ('photo', 'Photography on premises')], max_length=20)),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(blank=True, help_text='kiosk_signature · web_form · paper · verbal_to_staff', max_length=40)),
                ('evidence', models.CharField(blank=True, help_text='Signature file key, form id, or staff note.', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='guests.guest')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'guest consent',
                'verbose_name_plural': 'guest consents',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GuestDocument',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('nid', 'National ID'), ('driving_licence', 'Driving licence'), ('birth_certificate', 'Birth certificate'), ('other', 'Other')], max_length=20)),
                ('number', apps.core.fields.EncryptedTextField(verbose_name='document number')),
                ('issuing_country', models.CharField(blank=True, max_length=2)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('holder_name', models.CharField(blank=True, max_length=150)),
                ('scan', models.ImageField(blank=True, null=True, upload_to='guests/documents/%Y/%m/')),
                ('extracted', models.JSONField(blank=True, default=dict, help_text='Raw OCR field extraction, for audit.')),
                ('mrz_valid', models.BooleanField(blank=True, help_text='MRZ checksum result. Null means not checked.', null=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='guests.guest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'guest document',
                'verbose_name_plural': 'guest documents',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['tenant', 'last_name', 'first_name'], name='guests_gues_tenant__5e1f86_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['tenant', 'phone'], name='guests_gues_tenant__39ffe9_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['tenant', 'email'], name='guests_gues_tenant__d10a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='guestconsent',
            index=models.Index(fields=['guest', 'purpose', 'granted'], name='guests_gues_guest_i_6869fc_idx'),
        ),
        migrations.AddIndex(
            model_name='guestdocument',
            index=models.Index(fields=['guest', 'doc_type'], name='guests_gues_guest_i_f29783_idx'),
        ),
    ]
