# Generated by Django 5.2.16 on 2026-08-02 12:04

import apps.core.fields
import apps.core.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('key', models.SlugField(max_length=80, unique=True, verbose_name='key')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='what this prompt controls')),
                ('variables', models.JSONField(blank=True, default=list, help_text="Placeholder names the template accepts, e.g. ['guest_name', 'context'].")),
            ],
            options={
                'verbose_name': 'prompt template',
                'verbose_name_plural': 'prompt templates',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('kind', models.CharField(choices=[('llm', 'LLM (chat/completion)'), ('embedding', 'Text embedding'), ('image_embedding', 'Image embedding (CLIP)'), ('face', 'Face recognition'), ('stt', 'Speech to text'), ('tts', 'Text to speech'), ('ocr', 'OCR')], db_index=True, max_length=20, verbose_name='capability')),
                ('name', models.CharField(help_text='Shown in AI Center.', max_length=80, verbose_name='label')),
                ('provider', models.CharField(default='openai_compatible', help_text='openai_compatible · local_clip · local_insightface · paddleocr · fake', max_length=40, verbose_name='provider')),
                ('base_url', models.URLField(blank=True, verbose_name='endpoint')),
                ('api_key', apps.core.fields.EncryptedTextField(blank=True, default='', verbose_name='API key')),
                ('model_name', models.CharField(max_length=120, verbose_name='model')),
                ('temperature', models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_tokens', models.PositiveIntegerField(default=1024)),
                ('timeout_s', models.PositiveSmallIntegerField(default=30)),
                ('dimension', models.PositiveIntegerField(blank=True, help_text='Vector width. Must match the column it writes into.', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Exactly one default per hotel per capability.', verbose_name='default for this capability')),
                ('cost_per_1k_input_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cost_per_1k_output_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Provider-specific options.')),
                ('fallback', models.ForeignKey(blank=True, help_text='Used when this backend errors or times out.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for', to='ai_center.modelconfig')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'AI model configuration',
                'verbose_name_plural': 'AI model configurations',
                'ordering': ('kind', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False)), fields=('tenant', 'kind'), name='uniq_default_model_per_kind')],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('version', models.PositiveIntegerField(default=1)),
                ('system_prompt', models.TextField(verbose_name='system prompt')),
                ('user_template', models.TextField(blank=True, verbose_name='user message template')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='change note')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('eval_score', models.FloatField(blank=True, help_text='Latest tests/ai_eval score. A drop blocks activation (goal.txt D14).', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ai_center.prompttemplate')),
                ('tenant', models.ForeignKey(blank=True, help_text='Null = platform default, inherited by every hotel.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_versions', to='tenants.hotel')),
            ],
            options={
                'verbose_name': 'prompt version',
                'verbose_name_plural': 'prompt versions',
                'ordering': ('template__key', '-version'),
                'constraints': [models.UniqueConstraint(fields=('template', 'tenant', 'version'), name='uniq_prompt_version')],
            },
        ),
        migrations.CreateModel(
            name='SafetyPolicy',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('confidence_threshold', models.FloatField(default=0.55, help_text='Below this, the AI hands off to a human instead of answering.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_conversation_turns', models.PositiveSmallIntegerField(default=30)),
                ('session_token_cap', models.PositiveIntegerField(default=20000)),
                ('daily_cost_cap_usd', models.DecimalField(decimal_places=2, default=25, max_digits=8)),
                ('blocked_topics', models.JSONField(blank=True, default=list, help_text='Phrases the AI must refuse and escalate, e.g. medical advice.')),
                ('handoff_after_repeats', models.PositiveSmallIntegerField(default=2, help_text='Same question asked N times => notify staff (SRS Module 1 fallback).')),
                ('allow_financial_actions', models.BooleanField(default=False, help_text='Kept off: AI proposes, humans approve money movement (goal.txt D11).')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'AI safety policy',
                'verbose_name_plural': 'AI safety policies',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant',), name='uniq_safety_policy_per_hotel')],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('module', models.CharField(db_index=True, help_text='reception · rag · vision · housekeeping …', max_length=40)),
                ('kind', models.CharField(choices=[('llm', 'LLM (chat/completion)'), ('embedding', 'Text embedding'), ('image_embedding', 'Image embedding (CLIP)'), ('face', 'Face recognition'), ('stt', 'Speech to text'), ('tts', 'Text to speech'), ('ocr', 'OCR')], db_index=True, max_length=20)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('fallback_used', models.BooleanField(default=False)),
                ('cache_hit', models.BooleanField(default=False)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage', to='tenants.hotel')),
            ],
            options={
                'verbose_name': 'AI usage log',
                'verbose_name_plural': 'AI usage log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='ai_center_u_tenant__5cddca_idx'), models.Index(fields=['module', '-created_at'], name='ai_center_u_module_f9b97c_idx')],
            },
        ),
    ]
