# Generated by Django 5.2.16 on 2026-08-02 16:20

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_center', '0001_initial'),
        ('tenants', '0002_alter_hotel_check_in_time_alter_hotel_check_out_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelconfig',
            options={'ordering': ('kind', 'provider', 'name'), 'verbose_name': 'AI model configuration', 'verbose_name_plural': 'AI model configurations'},
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, help_text='Source system id, set by importers. Makes re-import idempotent.', max_length=80, verbose_name='imported from'),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='last_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, help_text='Last successful live round trip.', null=True),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='api_key',
            field=apps.core.fields.EncryptedTextField(blank=True, default='', help_text='Encrypted at rest. Shown masked once saved.', verbose_name='API key'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='base_url',
            field=models.URLField(blank=True, help_text='Leave blank to use the provider default. Required for self-hosted.', verbose_name='base URL'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific options as JSON, e.g. {"params": {"top_p": 0.9}, "api_key_header": "api-key"}.'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google AI Studio (Gemini)'), ('google', 'Google Cloud'), ('azure_openai', 'Azure OpenAI'), ('azure_speech', 'Azure Speech (TTS/STT)'), ('moonshot', 'Moonshot / Kimi'), ('zai', 'Z.ai'), ('groq', 'Groq'), ('openrouter', 'OpenRouter'), ('local', 'Local / self-hosted LLM'), ('openai_compatible', 'Other OpenAI-compatible endpoint'), ('local_clip', 'Local CLIP (image embedding)'), ('local_insightface', 'Local InsightFace'), ('paddleocr', 'PaddleOCR'), ('fake', 'Fake (tests and demos)'), ('other', 'Other')], db_index=True, default='openai_compatible', max_length=40, verbose_name='provider'),
        ),
        migrations.AddIndex(
            model_name='modelconfig',
            index=models.Index(fields=['provider', 'is_active'], name='ai_center_m_provide_73403d_idx'),
        ),
    ]
