# Generated by Django 5.2.16 on 2026-08-03 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_center', '0002_alter_modelconfig_options_modelconfig_created_by_and_more'),
        ('tenants', '0004_hotel_kiosk_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Leave blank to make this configuration apply to every hotel.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_model_configs', to='tenants.hotel'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False), ('tenant__isnull', True)), fields=('kind',), name='uniq_platform_default_model_per_kind'),
        ),
    ]
