# Generated by Django 5.2.16 on 2026-08-02 17:00

import apps.core.utils
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reception', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRoom',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('stay', django.contrib.postgres.fields.ranges.DateRangeField(help_text='[check-in, check-out) — the departure day belongs to the next guest.')),
                ('blocks_inventory', models.BooleanField(db_index=True, default=True)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('rate_snapshot', models.DecimalField(decimal_places=2, default=0, help_text='Average nightly rate as quoted.', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'room allocation',
                'verbose_name_plural': 'room allocations',
                'ordering': ('stay',),
            },
        ),
        migrations.CreateModel(
            name='StayEvent',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('kind', models.CharField(choices=[('check_in', 'Check-in'), ('check_out', 'Check-out'), ('room_move', 'Room move'), ('extend', 'Stay extended'), ('cancel', 'Cancelled'), ('no_show', 'Marked no-show')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'stay event',
                'verbose_name_plural': 'stay events',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('code', models.CharField(db_index=True, help_text='Read aloud over the phone; excludes ambiguous glyphs.', max_length=12, verbose_name='confirmation code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], db_index=True, default='pending', max_length=20)),
                ('source', models.CharField(choices=[('walk_in', 'Walk-in'), ('kiosk', 'AI kiosk'), ('phone', 'Phone'), ('website', 'Website'), ('ota', 'Online travel agent'), ('corporate', 'Corporate')], default='walk_in', max_length=20)),
                ('check_in', models.DateField(db_index=True)),
                ('check_out', models.DateField(db_index=True)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('special_requests', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('room_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('service_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='bookings/signatures/%Y/%m/')),
                ('conversation', models.ForeignKey(blank=True, help_text='Set when the AI kiosk took the booking. Links money to a transcript.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reception.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'ordering': ('-check_in', '-created_at'),
            },
        ),
    ]
