# Generated by Django 5.2.16 on 2026-08-02 17:00

import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_initial'),
        ('rooms', '0001_initial'),
        ('tenants', '0002_alter_hotel_check_in_time_alter_hotel_check_out_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rate_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rooms.rateplan'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel'),
        ),
        migrations.AddField(
            model_name='reservationroom',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='booking.reservation'),
        ),
        migrations.AddField(
            model_name='reservationroom',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Assigned at booking or at check-in; a type may be held first.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='reservationroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='rooms.roomtype'),
        ),
        migrations.AddField(
            model_name='reservationroom',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel'),
        ),
        migrations.AddField(
            model_name='stayevent',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stayevent',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='booking.reservation'),
        ),
        migrations.AddField(
            model_name='stayevent',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='stayevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['tenant', 'status', 'check_in'], name='booking_res_tenant__f57508_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['tenant', 'check_out'], name='booking_res_tenant__77bbd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'code'), name='uniq_reservation_code_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='reservation_at_least_one_night'),
        ),
        migrations.AddIndex(
            model_name='reservationroom',
            index=models.Index(fields=['reservation'], name='booking_res_reserva_07bdcf_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationroom',
            index=models.Index(fields=['room'], name='booking_res_room_id_2441c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservationroom',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('blocks_inventory', True), ('is_deleted', False), ('room__isnull', False)), expressions=[('room', '='), ('stay', '&&')], name='no_double_booked_room'),
        ),
        migrations.AddIndex(
            model_name='stayevent',
            index=models.Index(fields=['reservation', '-occurred_at'], name='booking_sta_reserva_cf7371_idx'),
        ),
    ]
