# Generated by Django 5.2.16 on 2026-08-02 17:00

import apps.core.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_hotel_check_in_time_alter_hotel_check_out_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='icon')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'amenity',
                'verbose_name_plural': 'amenities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('code', models.SlugField(max_length=24)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('includes_breakfast', models.BooleanField(default=False)),
                ('is_refundable', models.BooleanField(default=True)),
                ('min_nights', models.PositiveSmallIntegerField(default=1)),
                ('advance_days', models.PositiveSmallIntegerField(default=0, help_text='Must be booked at least this many days ahead.')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Applied to the room type base rate when no dated rate exists.', max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'rate plan',
                'verbose_name_plural': 'rate plans',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('number', models.CharField(max_length=12, verbose_name='room number')),
                ('floor', models.SmallIntegerField(default=1)),
                ('wing', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(choices=[('vacant_clean', 'Vacant clean'), ('vacant_dirty', 'Vacant dirty'), ('occupied', 'Occupied'), ('out_of_order', 'Out of order'), ('out_of_service', 'Out of service (maintenance)')], db_index=True, default='vacant_clean', max_length=20)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('out_of_order_until', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'ordering': ('floor', 'number'),
            },
        ),
        migrations.CreateModel(
            name='RoomStatusLog',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('from_status', models.CharField(blank=True, choices=[('vacant_clean', 'Vacant clean'), ('vacant_dirty', 'Vacant dirty'), ('occupied', 'Occupied'), ('out_of_order', 'Out of order'), ('out_of_service', 'Out of service (maintenance)')], max_length=20)),
                ('to_status', models.CharField(choices=[('vacant_clean', 'Vacant clean'), ('vacant_dirty', 'Vacant dirty'), ('occupied', 'Occupied'), ('out_of_order', 'Out of order'), ('out_of_service', 'Out of service (maintenance)')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='rooms.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'room status change',
                'verbose_name_plural': 'room status history',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('code', models.SlugField(max_length=24, verbose_name='code')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('description', models.TextField(blank=True)),
                ('base_occupancy', models.PositiveSmallIntegerField(default=2, verbose_name='standard occupancy')),
                ('max_occupancy', models.PositiveSmallIntegerField(default=3, verbose_name='maximum occupancy')),
                ('max_children', models.PositiveSmallIntegerField(default=2)),
                ('bed_type', models.CharField(choices=[('single', 'Single'), ('twin', 'Twin'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King'), ('bunk', 'Bunk')], default='double', max_length=20)),
                ('size_sqm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Fallback price when no rate plan matches the date.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='base rate per night')),
                ('extra_person_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('view', models.CharField(blank=True, help_text='sea · city · garden · pool — free text, surfaced to guests.', max_length=40, verbose_name='view')),
                ('is_smoking', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('amenities', models.ManyToManyField(blank=True, related_name='room_types', to='rooms.amenity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'room type',
                'verbose_name_plural': 'room types',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('valid_from', models.DateField(db_index=True)),
                ('valid_to', models.DateField(db_index=True, help_text='Inclusive.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Higher wins when ranges overlap.')),
                ('weekdays', models.CharField(blank=True, help_text='Comma-separated 0-6 (Mon-Sun). Blank means every day.', max_length=20)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rooms.rateplan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rooms.roomtype')),
            ],
            options={
                'verbose_name': 'room rate',
                'verbose_name_plural': 'room rates',
                'ordering': ('-priority', 'valid_from'),
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype'),
        ),
        migrations.AddConstraint(
            model_name='rateplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'code'), name='uniq_rate_plan_code_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='rateplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('is_deleted', False)), fields=('tenant',), name='uniq_default_rate_plan_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='roomstatuslog',
            index=models.Index(fields=['room', '-created_at'], name='rooms_rooms_room_id_d48784_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'code'), name='uniq_room_type_code_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.CheckConstraint(condition=models.Q(('max_occupancy__gte', models.F('base_occupancy'))), name='room_type_occupancy_sane'),
        ),
        migrations.AddIndex(
            model_name='roomrate',
            index=models.Index(fields=['room_type', 'rate_plan', 'valid_from', 'valid_to'], name='rooms_roomr_room_ty_713377_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomrate',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='room_rate_range_sane'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['tenant', 'status'], name='rooms_room_tenant__42fa2b_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type', 'status'], name='rooms_room_room_ty_a51164_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'number'), name='uniq_room_number_per_hotel'),
        ),
    ]
