# Generated by Django 5.2.16 on 2026-08-04 04:20

import apps.core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        ('tenants', '0007_hotel_kiosk_avatar_hotel_kiosk_backdrop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypePhoto',
            fields=[
                ('id', models.UUIDField(default=apps.core.utils.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('image', models.ImageField(upload_to='rooms/types/%Y/%m/', verbose_name='photo')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='caption')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lowest first. The first photo is the one the kiosk leads with.')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rooms.roomtype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'room photo',
                'verbose_name_plural': 'room photos',
                'ordering': ('sort_order', 'created_at'),
                'indexes': [models.Index(fields=['room_type', 'sort_order'], name='rooms_roomt_room_ty_2d8e91_idx')],
            },
        ),
    ]
